linters:
  enable:
    - depguard
    - forbidigo
    - gochecknoglobals
    - gochecknoinits
    - nolintlint
linters-settings:
  depguard:
    rules:
      main:
        deny:
          - pkg: "io/ioutil"
            desc: "`io/ioutil` is deprecated in Go 1.16, use `io` or `os` instead"
  errcheck:
    exclude-functions:
      - "io.WriteString(*text/tabwriter.Writer)"
  forbidigo:
    forbid:
      - '^os\.(DirEntry|FileInfo|FileMode|PathError)$' # deprecated in Go 1.16, import them from 'io/fs' instead
      - '\.Readdir$' # deprecated in Go 1.16, use ReadDir instead
  nolintlint:
    allow-unused: false
    allow-leading-space: false
    require-explanation: true
    require-specific: true
